# Generated by Django 3.2.20 on 2024-01-25 00:26
import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adserver_analyzer', '0002_last_ad_served_to_datefield'),
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS vector;'),
        migrations.AddField(
            model_name='analyzedurl',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, default=None, dimensions=3, null=True),
        ),
        migrations.AddField(
            model_name='historicalanalyzedurl',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, default=None, dimensions=3, null=True),
        ),
    ]
