# Generated by Django 4.2.11 on 2024-03-14 18:53
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adserver_analyzer", "0004_add_embeddings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analyzedurl",
            name="embedding",
        ),
        migrations.RemoveField(
            model_name="historicalanalyzedurl",
            name="embedding",
        ),
    ]
