# Generated by Django 4.2.11 on 2024-03-14 21:03
import django.db.models.deletion
import django_extensions.db.fields
import jsonfield.fields
from django.db import migrations
from django.db import models

import adserver.analyzer.validators


class Migration(migrations.Migration):

    dependencies = [
        ("adserver", "0093_publisher_ignore_mobile_traffic"),
        ("adserver_analyzer", "0005_remove_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyzedAd",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        db_index=True,
                        help_text="URL of the page being analyzed after certain query parameters are stripped away",
                        max_length=1024,
                    ),
                ),
                (
                    "keywords",
                    jsonfield.fields.JSONField(
                        blank=True,
                        null=True,
                        validators=[adserver.analyzer.validators.KeywordsValidator()],
                        verbose_name="Keywords for this URL",
                    ),
                ),
                (
                    "last_analyzed_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Last time the ad server analyzed this URL",
                        null=True,
                    ),
                ),
                (
                    "last_ad_served_date",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="Last date an ad was served for this URL",
                        null=True,
                    ),
                ),
                (
                    "visits_since_last_analyzed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times ads have been served for this URL since it was last analyzed",
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        help_text="Ad with the URL",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adserver.advertisement",
                    ),
                ),
            ],
            options={
                "unique_together": {("url", "ad")},
            },
        ),
        migrations.DeleteModel(
            name="HistoricalAnalyzedUrl",
        ),
    ]
