# Generated by Django 4.2.11 on 2024-03-26 21:25
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adserver_analyzer", "0005_add_analyzedad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analyzedadvertiserurl",
            name="embedding",
        ),
        migrations.RemoveField(
            model_name="analyzedurl",
            name="embedding",
        ),
    ]
