# Generated by Django 4.2.11 on 2024-03-21 22:21
import django.db.models.deletion
import django_extensions.db.fields
import jsonfield.fields
import pgvector.django
import simple_history.models
from django.conf import settings
from django.db import migrations
from django.db import models

import adserver.analyzer.validators


class Migration(migrations.Migration):

    dependencies = [
        ("adserver", "0093_publisher_ignore_mobile_traffic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adserver_analyzer", "0005_add_analyzedad"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalanalyzedurl",
            name="description",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Description of the page",
            ),
        ),
        migrations.AddField(
            model_name="historicalanalyzedurl",
            name="title",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Title of the page"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalAnalyzedAdvertiserUrl",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        db_index=True,
                        help_text="URL of the page being analyzed after certain query parameters are stripped away",
                        max_length=1024,
                    ),
                ),
                (
                    "keywords",
                    jsonfield.fields.JSONField(
                        blank=True,
                        null=True,
                        validators=[adserver.analyzer.validators.KeywordsValidator()],
                        verbose_name="Keywords for this URL",
                    ),
                ),
                (
                    "last_analyzed_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Last time the ad server analyzed this URL",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Title of the page",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Description of the page",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        blank=True, default=None, dimensions=384, null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "advertiser",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Advertiser with the URL",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="adserver.advertiser",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical analyzed advertiser url",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
