# Generated by Django 4.2.11 on 2024-03-14 21:45
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("adserver", "0093_publisher_ignore_mobile_traffic"),
        ("adserver_analyzer", "0007_rename_ad"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="analyzedad",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="analyzedad",
            name="advertiser",
            field=models.ForeignKey(
                default=1,
                help_text="Advertiser with the URL",
                on_delete=django.db.models.deletion.CASCADE,
                to="adserver.advertiser",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="analyzedad",
            unique_together={("url", "advertiser")},
        ),
        migrations.RemoveField(
            model_name="analyzedad",
            name="advertisement",
        ),
    ]
