# Generated by Django 5.0.14 on 2025-08-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver_analyzer', '0008_migrate_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedadvertiserurl',
            name='domain',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=1024, null=True, verbose_name='Domain'),
        ),
        migrations.AddField(
            model_name='analyzedurl',
            name='domain',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=1024, null=True, verbose_name='Domain'),
        ),
    ]
