# Generated by Django 5.0.14 on 2025-08-14 23:10

from django.db import migrations

from urllib.parse import urlparse


def get_domain_from_url(url):
    """This is re-implemented from utils in case the function every moves."""
    if not url:
        return None
    try:
        parsed = urlparse(url)
    except ValueError:
        return None
    return parsed.netloc


def forwards(apps, schema_editor):
    """Add the initial region and topic data."""
    AnalyzedUrl = apps.get_model("adserver_analyzer", "AnalyzedUrl")
    AnalyzedAdvertiserUrl = apps.get_model("adserver_analyzer", "AnalyzedAdvertiserUrl")

    for analyzed_url in AnalyzedUrl.objects.all():
        if not analyzed_url.domain:
            analyzed_url.domain = get_domain_from_url(analyzed_url.url)
            analyzed_url.save(update_fields=["domain"])

    for analyzed_advertiser_url in AnalyzedAdvertiserUrl.objects.all():
        if not analyzed_advertiser_url.domain:
            analyzed_advertiser_url.domain = get_domain_from_url(analyzed_advertiser_url.url)
            analyzed_advertiser_url.save(update_fields=["domain"])


class Migration(migrations.Migration):

    dependencies = [
        ('adserver_analyzer', '0009_domain_analyzed_url'),
    ]

    operations = [
        # No need to go backwards
        # The models these write to are deleted in the previous migration
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
