# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-14 22:35
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0003_publisher-advertiser-adtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='adimpression',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adserver.Publisher'),
        ),
        migrations.AddField(
            model_name='click',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adserver.Publisher'),
        ),
        migrations.AddField(
            model_name='view',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adserver.Publisher'),
        ),
        migrations.AlterUniqueTogether(
            name='adimpression',
            unique_together=set([('publisher', 'advertisement', 'date')]),
        ),
    ]
