# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-19 17:40
from __future__ import unicode_literals

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0004_impressions-models-for-publishers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adtype',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='adtype',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='adtype',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adtype',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertiser',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='flight',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
