# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-19 15:48
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0004_impressions-models-for-publishers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adtype',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='adtype',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertiser',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create date'),
            preserve_default=False,
        ),
    ]
