# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-19 16:03
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0005_pubdate-to-create-date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='publishers',
            field=models.ManyToManyField(blank=True, help_text='Ads for this campaign are eligible for display on these publishers', related_name='campaigns', to='adserver.Publisher'),
        ),
    ]
