# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-17 22:19
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0006_fix-related-name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimpression',
            name='clicks',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the ad was legitimately clicked', verbose_name='Clicks'),
        ),
        migrations.AlterField(
            model_name='adimpression',
            name='offers',
            field=models.PositiveIntegerField(default=0, help_text='The number of times an ad was proposed by the ad server. The client may not load the ad (a view) for a variety of reasons ', verbose_name='Offers'),
        ),
        migrations.AlterField(
            model_name='adimpression',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the ad was legitimately viewed', verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='sold_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Sold Clicks'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='sold_impressions',
            field=models.PositiveIntegerField(default=0, verbose_name='Sold Impressions'),
        ),
    ]
