# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-11 23:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0008_remove-click-date-autonow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='max_sale_value',
        ),
        migrations.AlterField(
            model_name='flight',
            name='priority_multiplier',
            field=models.IntegerField(default=1, help_text="Multiplies chance of showing this flight's ads [1,1000000]", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)], verbose_name='Priority Multiplier'),
        ),
    ]
