# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-17 04:41
from __future__ import unicode_literals

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0009_remove-campaign-max-sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='total_clicks',
            field=models.PositiveIntegerField(default=0, help_text='Clicks across all ads in this flight'),
        ),
        migrations.AddField(
            model_name='flight',
            name='total_views',
            field=models.PositiveIntegerField(default=0, help_text='Views across all ads in this flight'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start_date',
            field=models.DateField(db_index=True, default=datetime.date.today, help_text='This ad will not be shown before this date', verbose_name='Start Date'),
        ),
    ]
