# Generated by Django 2.2.10 on 2020-03-07 04:57
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0013_affiliate-campaigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='advertiser',
            field=models.ForeignKey(help_text='The advertiser for this campaign.', on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='adserver.Advertiser'),
        ),
    ]
