# Generated by Django 2.2.10 on 2020-03-23 18:46
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0014_enforce_campaign_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='unauthed_ad_decisions',
            field=models.BooleanField(default=False, help_text='Whether this publisher allows unauthenticated ad decision API requests (eg. JSONP)'),
        ),
    ]
