# Generated by Django 2.2.10 on 2020-05-12 03:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0015_publisher_unauthed_ads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adtype',
            options={'ordering': ('order', 'name')},
        ),
        migrations.AddField(
            model_name='adtype',
            name='description',
            field=models.CharField(blank=True, default='', help_text='A short description of the ad type to guide advertisers.', max_length=255),
        ),
        migrations.AddField(
            model_name='adtype',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
