# Generated by Django 2.2.13 on 2020-06-29 21:38
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0016_ad_type_additions'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='revenue_share_percentage',
            field=models.FloatField(default=50.0, help_text='Percentage of advertising revenue shared with this publisher', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
