# Generated by Django 2.2.13 on 2020-06-30 19:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0017_revshare_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='paid_campaigns_only',
            field=models.BooleanField(default=False, help_text='Only show paid campaigns for this publisher'),
        ),
    ]
