# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-03 17:08
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0018_paid_ads_only_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='default_keywords',
            field=models.CharField(blank=True, default='', help_text='A CSV of default keywords for this property. Used for targeting.', max_length=250, verbose_name='Default keywords'),
        ),
    ]
