# Generated by Django 2.2.13 on 2020-07-02 03:33
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0018_paid_ads_only_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='paid_campaigns_only',
            field=models.BooleanField(default=True, help_text='Only show paid campaigns for this publisher'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='unauthed_ad_decisions',
            field=models.BooleanField(default=True, help_text='Whether this publisher allows unauthenticated ad decision API requests (eg. JSONP)'),
        ),
    ]
