# Generated by Django 2.2.13 on 2020-07-06 18:19
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0020_add_default_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='record_views',
            field=models.BooleanField(default=False, help_text='Record each ad view from this publisher to the database'),
        ),
    ]
