# Generated by Django 2.2.13 on 2020-07-07 04:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0021_publisher_record_ad_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adtype',
            name='publisher',
        ),
        migrations.AddField(
            model_name='adtype',
            name='default_enabled',
            field=models.BooleanField(default=False, help_text='Whether this ad type should default to checked when advertisers are creating ads'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_types',
            field=models.ManyToManyField(blank=True, help_text='Possible ways this ad will be displayed', related_name='advertisements', to='adserver.AdType'),
        ),
    ]
