# Generated by Django 2.2.13 on 2020-07-14 04:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0023_data_migrate_ad_type_to_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Stripe Customer ID'),
        ),
    ]
