# Generated by Django 2.2.13 on 2020-07-17 22:03
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0024_advertiser_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='allow_affiliate_campaigns',
            field=models.BooleanField(default=False, verbose_name='Allow affiliate campaigns'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='allow_community_campaigns',
            field=models.BooleanField(default=True, verbose_name='Allow community campaigns'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='allow_house_campaigns',
            field=models.BooleanField(default=True, verbose_name='Allow house campaigns'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='allow_paid_campaigns',
            field=models.BooleanField(default=True, verbose_name='Allow paid campaigns'),
        ),
    ]
