# Generated by Django 2.2.13 on 2020-08-03 22:52
import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0027_refunded_impressions_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherPayout',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Amount')),
                ('date', models.DateTimeField(verbose_name='Payout date')),
                ('note', models.TextField(blank=True, help_text='A publisher-visible note about the payout', null=True, verbose_name='Note')),
                ('attachment', models.FileField(blank=True, help_text='A publisher-visible attachment such as a receipt', max_length=255, null=True, upload_to='payouts/%Y/%m/', verbose_name='Attachment')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='adserver.Publisher')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
