# Generated by Django 2.2.13 on 2020-08-04 04:47
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0027_refunded_impressions_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='allow_paid_campaigns',
            field=models.BooleanField(default=False, verbose_name='Allow paid campaigns'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='record_views',
            field=models.BooleanField(default=True, help_text='Record each ad view from this publisher to the database'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='revenue_share_percentage',
            field=models.FloatField(default=70.0, help_text='Percentage of advertising revenue shared with this publisher', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
