# Generated by Django 2.2.13 on 2020-08-19 21:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0030_publisher_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='open_collective_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Open Collective name'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe (Bank transfer, debit card)'), ('paypal', 'PayPal'), ('opencollective', 'Open Collective'), ('other', 'Other')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='paypal_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='PayPal email address'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='stripe_connected_account_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Stripe connected account ID'),
        ),
        migrations.AddField(
            model_name='publisherpayout',
            name='method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe (Bank transfer, debit card)'), ('paypal', 'PayPal'), ('opencollective', 'Open Collective'), ('other', 'Other')], default=None, max_length=100, null=True),
        ),
    ]
