# Generated by Django 2.2.13 on 2020-09-16 21:04
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0031_publisher_payout_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisherpayout',
            options={'ordering': ('date',)},
        ),
    ]
