# Generated by Django 2.2.13 on 2020-09-28 23:24
import uuid

import django.db.models.deletion
import django_countries.fields
import django_extensions.db.fields
import jsonfield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0032_update_sort_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='ad_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='adserver.AdType'),
        ),
        migrations.AddField(
            model_name='click',
            name='div_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Placement on the client'),
        ),
        migrations.AddField(
            model_name='click',
            name='keywords',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Keyword targeting for this view'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='record_placements',
            field=models.BooleanField(default=False, help_text='Record placement impressions for this publisher'),
        ),
        migrations.AddField(
            model_name='view',
            name='ad_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='adserver.AdType'),
        ),
        migrations.AddField(
            model_name='view',
            name='div_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Placement on the client'),
        ),
        migrations.AddField(
            model_name='view',
            name='keywords',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Keyword targeting for this view'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateTimeField(verbose_name='Impression date')),
                ('ip', models.GenericIPAddressField(verbose_name='Ip Address')),
                ('user_agent', models.CharField(blank=True, max_length=1000, null=True, verbose_name='User Agent')),
                ('client_id', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Client ID')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('url', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Page URL')),
                ('browser_family', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Browser Family')),
                ('os_family', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Operating System Family')),
                ('keywords', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Keyword targeting for this view')),
                ('div_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Placement on the client')),
                ('is_bot', models.BooleanField(default=False)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_refunded', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed', models.BooleanField(default=False, verbose_name='Offer was viewed')),
                ('clicked', models.BooleanField(default=False, verbose_name='Offer was clicked')),
                ('ad_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='adserver.AdType')),
                ('advertisement', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='adserver.Advertisement')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adserver.Publisher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlacementImpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(verbose_name='Date')),
                ('offers', models.PositiveIntegerField(default=0, help_text='The number of times an ad was proposed by the ad server. The client may not load the ad (a view) for a variety of reasons ', verbose_name='Offers')),
                ('views', models.PositiveIntegerField(default=0, help_text='Number of times the ad was legitimately viewed', verbose_name='Views')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Number of times the ad was legitimately clicked', verbose_name='Clicks')),
                ('div_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_impressions', to='adserver.AdType')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_impressions', to='adserver.Advertisement')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_impressions', to='adserver.Publisher')),
            ],
            options={
                'verbose_name_plural': 'Placement impressions',
                'ordering': ('-date',),
                'unique_together': {('publisher', 'advertisement', 'date', 'div_id', 'ad_type')},
            },
        ),
    ]
