# Generated by Django 2.2.13 on 2020-09-18 00:11
import django.db.models.deletion
import django_extensions.db.fields
import jsonfield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0032_update_sort_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='keywords',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Keyword targeting for this view'),
        ),
        migrations.AddField(
            model_name='click',
            name='placement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Placement on the client'),
        ),
        migrations.AddField(
            model_name='view',
            name='keywords',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Keyword targeting for this view'),
        ),
        migrations.AddField(
            model_name='view',
            name='placement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Placement on the client'),
        ),
        migrations.CreateModel(
            name='PlacementImpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(verbose_name='Date')),
                ('offers', models.PositiveIntegerField(default=0, help_text='The number of times an ad was proposed by the ad server. The client may not load the ad (a view) for a variety of reasons ', verbose_name='Offers')),
                ('views', models.PositiveIntegerField(default=0, help_text='Number of times the ad was legitimately viewed', verbose_name='Views')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Number of times the ad was legitimately clicked', verbose_name='Clicks')),
                ('placement', models.CharField(blank=True, max_length=255, null=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_impressions', to='adserver.Advertisement')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_impressions', to='adserver.Publisher')),
            ],
            options={
                'verbose_name_plural': 'Placement impressions',
                'ordering': ('-date',),
                'unique_together': {('publisher', 'advertisement', 'date', 'placement')},
            },
        ),
    ]
