# Generated by Django 2.2.13 on 2020-10-22 23:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0035_add_geoimpressions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='allow_community_campaigns',
            field=models.BooleanField(default=True, help_text='These are unpaid campaigns that support non-profit projects in our community. Shown only when no paid ads are available', verbose_name='Allow community campaigns'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='allow_house_campaigns',
            field=models.BooleanField(default=True, help_text='These are ads for EthicalAds itself. Shown only when no paid ads are available.', verbose_name='Allow house campaigns'),
        ),
    ]
