# Generated by Django 2.2.13 on 2020-11-02 22:41
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0038_offer_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='adimpression',
            name='decisions',
            field=models.PositiveIntegerField(default=0, help_text="The number of times the Ad Decision API was called. The server might not respond with an ad if there isn't inventory.", verbose_name='Decisions'),
        ),
        migrations.AddField(
            model_name='geoimpression',
            name='decisions',
            field=models.PositiveIntegerField(default=0, help_text="The number of times the Ad Decision API was called. The server might not respond with an ad if there isn't inventory.", verbose_name='Decisions'),
        ),
        migrations.AddField(
            model_name='placementimpression',
            name='decisions',
            field=models.PositiveIntegerField(default=0, help_text="The number of times the Ad Decision API was called. The server might not respond with an ad if there isn't inventory.", verbose_name='Decisions'),
        ),
        migrations.AlterField(
            model_name='adimpression',
            name='advertisement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impressions', to='adserver.Advertisement'),
        ),
    ]
