# Generated by Django 2.2.13 on 2020-11-09 22:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0038_offer_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='uplifted',
            field=models.BooleanField(default=None, null=True, verbose_name='Attribute Offer to uplift'),
        ),
    ]
