# Generated by Django 2.2.13 on 2020-11-13 03:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0039_add_uplift'),
    ]

    operations = [
        migrations.AddField(
            model_name='adtype',
            name='deprecated',
            field=models.BooleanField(default=False, help_text='Users cannot select deprecated ad types unless an ad is already that type.'),
        ),
    ]
