# Generated by Django 2.2.13 on 2020-11-02 23:12
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0039_add_decisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoimpression',
            name='advertisement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='geo_impressions', to='adserver.Advertisement'),
        ),
        migrations.AlterField(
            model_name='placementimpression',
            name='advertisement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placement_impressions', to='adserver.Advertisement'),
        ),
    ]
