# Generated by Django 2.2.13 on 2020-11-20 01:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0042_add_keyword_impressions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='render_pixel',
            field=models.BooleanField(default=False, help_text='Render ethical-pixel in ad templates. This is needed for users not using the ad client.'),
        ),
    ]
