# Generated by Django 2.2.13 on 2020-12-14 20:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0045_add_uplift_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='body',
            field=models.TextField(blank=True, help_text='For most ad types, the combined length of the headline, body, and call to action should be less than 100 characters.', null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='cta',
            field=models.CharField(blank=True, help_text='An optional call to action displayed at the end of the ad usually in bold', max_length=200, null=True, verbose_name='Call to action'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='headline',
            field=models.CharField(blank=True, help_text='An optional headline at the end of the ad usually displayed in bold', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='text',
            field=models.TextField(blank=True, help_text='For most ad types, the text should be less than 100 characters.', verbose_name='Text'),
        ),
    ]
