# Generated by Django 2.2.13 on 2020-12-08 04:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0045_add_uplift_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='exclude_publishers',
            field=models.ManyToManyField(blank=True, help_text='Ads for this campaign will not be shown on these publishers', to='adserver.Publisher'),
        ),
    ]
