# Generated by Django 2.2.13 on 2021-01-21 17:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0048_null_offer_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='headline',
            field=models.CharField(blank=True, help_text='An optional headline at the beginning of the ad usually displayed in bold', max_length=200, null=True),
        ),
    ]
