# Generated by Django 2.2.20 on 2021-04-28 02:05
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0050_link_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adtype',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Advertiser Slug'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Campaign Slug'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Flight Slug'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Publisher Slug'),
        ),
        migrations.AlterField(
            model_name='publishergroup',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Publisher group slug'),
        ),
    ]
