# Generated by Django 2.2.13 on 2021-06-11 00:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0051_unique_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherpayout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('hold', 'On hold'), ('emailed', 'Email sent'), ('paid', 'Payment sent')], default='pending', help_text='Status of this payout', max_length=50),
        ),
    ]
