# Generated by Django 2.2.20 on 2021-06-12 21:51
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0051_unique_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='sampled_ctr',
            field=models.FloatField(default=0.0, help_text='A periodically calculated CTR from a sample of ads on this publisher.'),
        ),
    ]
