# Generated by Django 2.2.13 on 2021-06-14 20:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0052_add_payout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherpayout',
            name='end_date',
            field=models.DateField(help_text='Last day of paid period', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='publisherpayout',
            name='start_date',
            field=models.DateField(help_text='First day of paid period', null=True, verbose_name='Start Date'),
        ),
    ]
