# Generated by Django 2.2.24 on 2021-07-13 21:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0055_adding_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='adtype',
            name='publisher_groups',
            field=models.ManyToManyField(blank=True, help_text='This is used for ad types specific to certain publishers. By default, an ad type is global for all publishers.', related_name='adtypes', to='adserver.PublisherGroup'),
        ),
    ]
