# Generated by Django 2.2.24 on 2021-08-18 20:59
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0058_view_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublisher',
            name='skip_payouts',
            field=models.BooleanField(default=False, help_text='Enable this to temporarily disable payouts. They will be processed again once you uncheck this.', verbose_name='Skip payouts'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='skip_payouts',
            field=models.BooleanField(default=False, help_text='Enable this to temporarily disable payouts. They will be processed again once you uncheck this.', verbose_name='Skip payouts'),
        ),
    ]
