# Generated by Django 2.2.24 on 2021-09-16 00:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0060_update_region_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublisher',
            name='cache_ads',
            field=models.BooleanField(default=True, help_text='Cache this publishers ad requests. Disable for special cases (eg. SaaS users)'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='cache_ads',
            field=models.BooleanField(default=True, help_text='Cache this publishers ad requests. Disable for special cases (eg. SaaS users)'),
        ),
    ]
