# Generated by Django 2.2.24 on 2022-01-25 23:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0061_add_uncached_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublisher',
            name='saas',
            field=models.BooleanField(default=False, help_text='This published is configured as a SaaS customer. They will be billed by usage instead of paid out.'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='saas',
            field=models.BooleanField(default=False, help_text='This published is configured as a SaaS customer. They will be billed by usage instead of paid out.'),
        ),
    ]
