# Generated by Django 2.2.26 on 2022-02-08 00:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0065_flight_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublisher',
            name='disabled',
            field=models.BooleanField(default=False, help_text='Completely disable this publisher'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='disabled',
            field=models.BooleanField(default=False, help_text='Completely disable this publisher'),
        ),
    ]
