# Generated by Django 3.2.13 on 2022-05-12 22:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0067_add_adimpression_viewtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublisher',
            name='daily_cap',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='A daily maximum this publisher can earn after which only unpaid ads are shown.', max_digits=8, null=True, verbose_name='Daily maximum earn cap'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='daily_cap',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='A daily maximum this publisher can earn after which only unpaid ads are shown.', max_digits=8, null=True, verbose_name='Daily maximum earn cap'),
        ),
    ]
