# Generated by Django 3.2.13 on 2022-05-17 18:47
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0068_add_publisher_daily_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='publisher',
            field=models.ForeignKey(blank=True, default=None, help_text='Used for advertiser accounts associated with a publisher', null=True, on_delete=django.db.models.deletion.PROTECT, to='adserver.publisher'),
        ),
        migrations.AddField(
            model_name='historicaladvertiser',
            name='publisher',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, help_text='Used for advertiser accounts associated with a publisher', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='adserver.publisher'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('paid', 'Paid'), ('affiliate', 'Affiliate'), ('community', 'Community'), ('publisher-house', 'Publisher House'), ('house', 'House')], default='paid', help_text='Most campaigns are paid but ad server admins can configure other lower priority campaign types.', max_length=20, verbose_name='Campaign Type'),
        ),
        migrations.AlterField(
            model_name='historicalcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('paid', 'Paid'), ('affiliate', 'Affiliate'), ('community', 'Community'), ('publisher-house', 'Publisher House'), ('house', 'House')], default='paid', help_text='Most campaigns are paid but ad server admins can configure other lower priority campaign types.', max_length=20, verbose_name='Campaign Type'),
        ),
    ]
