"""
Adds default region and topic data.
"""
from django.db import migrations


# This is snapshotted from regiontopics.py
# We don't import that module since that could change after this migration is released
REGIONS = {
    "us-ca": {
        "order": 0,
        "countries": ["US", "CA"],
    },
    "eu-aus-nz": {
        "order": 0,
        "countries": [
            "DE",
            "GB",
            "FR",
            "IT",
            "ES",
            "CH",
            "NL",
            "PT",
            "AT",
            "BE",
            "LU",
            "IE",
            "GR",
            "SE",
            "DK",
            "NO",
            "FI",
            # Vaguely Eastern Europe but still EU
            "PL",
            "LV",
            "LT",
            "EE",
            "BG",
            "HR",
            "RO",
            "SK",
            "SI",
            "HU",
            "CZ",
            # Bundled into Europe
            "IS",
            "IL",
            # Australia and New Zealand
            "AU",
            "NZ",
        ],
    },
    "wider-apac": {
        "order": 0,
        "countries": [
            "SG",
            "HK",
            "JP",
            "KR",
            "TW",
        ],
    },
    "latin-america": {
        "order": 0,
        "countries": [
            "AI",
            "AR",
            "AW",
            "BS",
            "BB",
            "BZ",
            "BM",
            "BO",
            "VG",
            "KY",
            "CL",
            "CO",
            "CR",
            "CU",
            "CW",
            "DM",
            "DO",
            "EC",
            "SV",
            "FK",
            "GL",
            "GP",
            "GT",
            "GY",
            "HT",
            "HN",
            "JM",
            "MX",
            "MS",
            "NI",
            "PA",
            "PY",
            "PE",
            "PR",
            "BL",
            "KN",
            "LC",
            "MF",
            "PM",
            "VC",
            "SR",
            "TT",
            "UY",
            "VE",
            "BR",
        ],
    },
    "africa": {
        "order": 0,
        "countries": [
            "DZ",
            "AO",
            "BJ",
            "BW",
            "BF",
            "BI",
            "CM",
            "CV",
            "CF",
            "KM",
            "CD",
            "DJ",
            "EG",
            "GQ",
            "ER",
            "ET",
            "GA",
            "GM",
            "GH",
            "GN",
            "GW",
            "CI",
            "KE",
            "LS",
            "LR",
            "LY",
            "MG",
            "MW",
            "ML",
            "MR",
            "MU",
            "MA",
            "MZ",
            "NA",
            "NE",
            "NG",
            "CG",
            "RE",
            "RW",
            "SH",
            "ST",
            "SN",
            "SC",
            "SL",
            "SO",
            "ZA",
            "SS",
            "SD",
            "SZ",
            "TZ",
            "TG",
            "TN",
            "UG",
            "EH",
            "ZM",
            "ZW",
        ],
    },
    "south-asia": {
        "order": 0,
        "countries": ["IN"],
    },
    "eu": {
        "order": 1,
        "countries": [
            "DE",
            # "GB",
            "FR",
            "IT",
            "ES",
            # "CH",
            "NL",
            "PT",
            "AT",
            "BE",
            "LU",
            "IE",
            "GR",
            "SE",
            "DK",
            # "NO",
            "FI",
            "PL",
            "LV",
            "LT",
            "EE",
            "BG",
            "HR",
            "RO",
            "SK",
            "SI",
            "HU",
            "CZ",
        ],
    },
    "dach": {
        "order": 2,
        "countries": [
            "DE",
            "CH",
            "AT",
        ],
    },
    "aus-nz": {
        "order": 2,
        "countries": [
            "AU",
            "NZ",
        ],
    },
    "exclude": {
        "order": 0,
        # Tor (T1) isn't a real country code but is used by Cloudflare
        "countries": ["T1", "CN", "ID", "RU", "VN", "IR"],
    },
    "global": {
        "order": 9999,
        "countries": [
            "AF",
            "AX",
            "AL",
            "DZ",
            "AS",
            "AD",
            "AO",
            "AI",
            "AQ",
            "AG",
            "AR",
            "AM",
            "AW",
            "AU",
            "AT",
            "AZ",
            "BS",
            "BH",
            "BD",
            "BB",
            "BY",
            "BE",
            "BZ",
            "BJ",
            "BM",
            "BT",
            "BO",
            "BQ",
            "BA",
            "BW",
            "BV",
            "BR",
            "IO",
            "BN",
            "BG",
            "BF",
            "BI",
            "CV",
            "KH",
            "CM",
            "CA",
            "KY",
            "CF",
            "TD",
            "CL",
            "CN",
            "CX",
            "CC",
            "CO",
            "KM",
            "CG",
            "CD",
            "CK",
            "CR",
            "CI",
            "HR",
            "CU",
            "CW",
            "CY",
            "CZ",
            "DK",
            "DJ",
            "DM",
            "DO",
            "EC",
            "EG",
            "SV",
            "GQ",
            "ER",
            "EE",
            "SZ",
            "ET",
            "FK",
            "FO",
            "FJ",
            "FI",
            "FR",
            "GF",
            "PF",
            "TF",
            "GA",
            "GM",
            "GE",
            "DE",
            "GH",
            "GI",
            "GR",
            "GL",
            "GD",
            "GP",
            "GU",
            "GT",
            "GG",
            "GN",
            "GW",
            "GY",
            "HT",
            "HM",
            "VA",
            "HN",
            "HK",
            "HU",
            "IS",
            "IN",
            "ID",
            "IR",
            "IQ",
            "IE",
            "IM",
            "IL",
            "IT",
            "JM",
            "JP",
            "JE",
            "JO",
            "KZ",
            "KE",
            "KI",
            "KW",
            "KG",
            "LA",
            "LV",
            "LB",
            "LS",
            "LR",
            "LY",
            "LI",
            "LT",
            "LU",
            "MO",
            "MG",
            "MW",
            "MY",
            "MV",
            "ML",
            "MT",
            "MH",
            "MQ",
            "MR",
            "MU",
            "YT",
            "MX",
            "FM",
            "MD",
            "MC",
            "MN",
            "ME",
            "MS",
            "MA",
            "MZ",
            "MM",
            "NA",
            "NR",
            "NP",
            "NL",
            "NC",
            "NZ",
            "NI",
            "NE",
            "NG",
            "NU",
            "NF",
            "KP",
            "MK",
            "MP",
            "NO",
            "OM",
            "PK",
            "PW",
            "PS",
            "PA",
            "PG",
            "PY",
            "PE",
            "PH",
            "PN",
            "PL",
            "PT",
            "PR",
            "QA",
            "RE",
            "RO",
            "RU",
            "RW",
            "BL",
            "SH",
            "KN",
            "LC",
            "MF",
            "PM",
            "VC",
            "WS",
            "SM",
            "ST",
            "SA",
            "SN",
            "RS",
            "SC",
            "SL",
            "SG",
            "SX",
            "SK",
            "SI",
            "SB",
            "SO",
            "ZA",
            "GS",
            "KR",
            "SS",
            "ES",
            "LK",
            "SD",
            "SR",
            "SJ",
            "SE",
            "CH",
            "SY",
            "TW",
            "TJ",
            "TZ",
            "TH",
            "TL",
            "TG",
            "TK",
            "TO",
            "TT",
            "TN",
            "TR",
            "TM",
            "TC",
            "TV",
            "UG",
            "UA",
            "AE",
            "GB",
            "UM",
            "US",
            "UY",
            "UZ",
            "VU",
            "VE",
            "VN",
            "VG",
            "VI",
            "WF",
            "EH",
            "YE",
            "ZM",
            "ZW",
            "T1",
        ],
    },
}

TOPICS = {
    "data-science": [
        "data-science",
        "datascience",
        "ml",
        "training-data",
        "model-training",
        "machine-learning",
        "machinelearning",
        "sentiment-analysis",
        "ai",
        "artificial-intelligence",
        "neural-net",
        "neural-nets",
        "data-analytics",
        "visualization",
        "data-visualization",
        "nlp",
        "object-detection",
        "computer-vision",
        "jupyter",
        "matplotlib",
        "deep-learning",
        "pytorch",
        "pydata",
        "opencv-python-library",
        "pandas",
        "numpy",
        "tensor",
        "tensorflow",
    ],
    "backend-web": [
        "backend",
        "backend-web",
        "flask",
        "django",
        "werkzeug",
        "wsgi",
        "celery",
        "jinja",
    ],
    "frontend-web": [
        "frontend",
        "frontend-web",
        "javascript",
        "react",
        "reactjs",
        "css",
        "angular",
        "angularjs",
        "jquery",
        "vuejs",
        "vue",
        "webpack",
        "node",
        "nodejs",
    ],
    "security-privacy": ["security", "privacy", "cryptography", "oauth", "authorization", "authentication"],
    "devops": [
        "devops",
        "cloud",
        "docker",
        "kubernetes",
        "container",
        "containers",
        "ansible",
        "serverless",
        "openshift",
        "aws",
        "linux",
        "ubuntu",
        "monitoring",
        "openid-connect",
        "oauth",
        "redis",
        "rabbitmq",
        "nosql",
        "postgres",
        "postgresql",
        "mysql",
        "database",
        "elasticsearch",
        "lucene",
        "solr",
        "terraform",
        "nginx",
    ],
    "python": ["python", "django", "flask"],
    "game-dev": ["gamedev", "minecraft", "godot", "game"],
    "blockchain": [
        "blockchain",
        "ethereum",
        "bitcoin",
        "cryptocurrency",
        "hyperledger",
        "solidity",
    ],
    "techwriting": ["technical-writing", "sphinx", "sphinx-doc", "mkdocs"],
    "other": [],
}


def forwards(apps, schema_editor):
    """Add the initial region and topic data."""
    Topic = apps.get_model("adserver", "Topic")
    Keyword = apps.get_model("adserver", "Keyword")
    Region = apps.get_model("adserver", "Region")
    CountryRegion = apps.get_model("adserver", "CountryRegion")

    if Region.objects.all().count() == 0:
        for slug in REGIONS:
            region = Region.objects.create(
                slug=slug,
                order=REGIONS[slug]["order"],
            )

            for code in REGIONS[slug]["countries"]:
                CountryRegion.objects.create(
                    country=code,
                    region=region,
                )

    if Topic.objects.all().count() == 0:
        for slug in TOPICS:
            topic = Topic.objects.create(
                slug=slug,
            )

            for keyword in TOPICS[slug]:
                kw, _ = Keyword.objects.get_or_create(
                    slug=keyword,
                )
                topic.keywords.add(kw)


class Migration(migrations.Migration):

    dependencies = [
        ("adserver", "0070_region_topic_modeling"),
    ]

    operations = [
        # No need to go backwards
        # The models these write to are deleted in the previous migration
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
