"""
Adds default region and topic data.
"""
from django.db import migrations


# This is snapshotted from regiontopics.py
# We don't import that module since that could change after this migration is released
REGIONS = {
    "us-ca": {
        "name": "US & Canada",
        "order": 0,
        "countries": ["US", "CA"],
    },
    "wider-apac": {
        "name": "Wider APAC",
        "order": 0,
        "countries": [
            "SG",
            "HK",
            "JP",
            "KR",
            "TW",
        ],
    },
    "latin-america": {
        "name": "Latin America",
        "order": 5,
        "countries": [
            "AI",
            "AR",
            "AW",
            "BS",
            "BB",
            "BZ",
            "BM",
            "BO",
            "VG",
            "KY",
            "CL",
            "CO",
            "CR",
            "CU",
            "CW",
            "DM",
            "DO",
            "EC",
            "SV",
            "FK",
            "GL",
            "GP",
            "GT",
            "GY",
            "HT",
            "HN",
            "JM",
            "MX",
            "MS",
            "NI",
            "PA",
            "PY",
            "PE",
            "PR",
            "BL",
            "KN",
            "LC",
            "MF",
            "PM",
            "VC",
            "SR",
            "TT",
            "UY",
            "VE",
            "BR",
        ],
    },
    "africa": {
        "name": "Africa",
        "order": 10,
        "countries": [
            "DZ",
            "AO",
            "BJ",
            "BW",
            "BF",
            "BI",
            "CM",
            "CV",
            "CF",
            "KM",
            "CD",
            "DJ",
            "EG",
            "GQ",
            "ER",
            "ET",
            "GA",
            "GM",
            "GH",
            "GN",
            "GW",
            "CI",
            "KE",
            "LS",
            "LR",
            "LY",
            "MG",
            "MW",
            "ML",
            "MR",
            "MU",
            "MA",
            "MZ",
            "NA",
            "NE",
            "NG",
            "CG",
            "RE",
            "RW",
            "SH",
            "ST",
            "SN",
            "SC",
            "SL",
            "SO",
            "ZA",
            "SS",
            "SD",
            "SZ",
            "TZ",
            "TG",
            "TN",
            "UG",
            "EH",
            "ZM",
            "ZW",
        ],
    },
    "south-asia": {
        "name": "South Asia",
        "order": 5,
        "countries": ["IN"],
    },
    "eu-aus-nz": {
        "name": "Europe, Australia, & New Zealand",
        "order": 0,
        "countries": [
            "DE",
            "GB",
            "FR",
            "IT",
            "ES",
            "CH",
            "NL",
            "PT",
            "AT",
            "BE",
            "LU",
            "IE",
            "GR",
            "SE",
            "DK",
            "NO",
            "FI",
            "PL",
            "LV",
            "LT",
            "EE",
            "BG",
            "HR",
            "RO",
            "SK",
            "SI",
            "HU",
            "CZ",
            "IS",
            "IL",
            "AU",
            "NZ",
        ],
    },
    "eu": {
        "name": "European Union",
        "order": 2,
        "countries": [
            "DE",
            # "GB",
            "FR",
            "IT",
            "ES",
            # "CH",
            "NL",
            "PT",
            "AT",
            "BE",
            "LU",
            "IE",
            "GR",
            "SE",
            "DK",
            # "NO",
            "FI",
            "PL",
            "LV",
            "LT",
            "EE",
            "BG",
            "HR",
            "RO",
            "SK",
            "SI",
            "HU",
            "CZ",
        ],
    },
    "dach": {
        "name": "German speaking (DACH)",
        "order": 4,
        "countries": [
            "DE",
            "CH",
            "AT",
        ],
    },
    "aus-nz": {
        "name": "Australia & New Zealand",
        "order": 3,
        "countries": [
            "AU",
            "NZ",
        ],
    },
    "exclude": {
        "name": "Commonly excluded countries",
        "order": 10,
        # Tor (T1) isn't a real country code but is used by Cloudflare
        "countries": ["T1", "CN", "ID", "RU", "VN", "IR"],
    },
    "global": {
        "name": "All countries",
        "order": 9999,
        "countries": [
            "AF",
            "AX",
            "AL",
            "DZ",
            "AS",
            "AD",
            "AO",
            "AI",
            "AQ",
            "AG",
            "AR",
            "AM",
            "AW",
            "AU",
            "AT",
            "AZ",
            "BS",
            "BH",
            "BD",
            "BB",
            "BY",
            "BE",
            "BZ",
            "BJ",
            "BM",
            "BT",
            "BO",
            "BQ",
            "BA",
            "BW",
            "BV",
            "BR",
            "IO",
            "BN",
            "BG",
            "BF",
            "BI",
            "CV",
            "KH",
            "CM",
            "CA",
            "KY",
            "CF",
            "TD",
            "CL",
            "CN",
            "CX",
            "CC",
            "CO",
            "KM",
            "CG",
            "CD",
            "CK",
            "CR",
            "CI",
            "HR",
            "CU",
            "CW",
            "CY",
            "CZ",
            "DK",
            "DJ",
            "DM",
            "DO",
            "EC",
            "EG",
            "SV",
            "GQ",
            "ER",
            "EE",
            "SZ",
            "ET",
            "FK",
            "FO",
            "FJ",
            "FI",
            "FR",
            "GF",
            "PF",
            "TF",
            "GA",
            "GM",
            "GE",
            "DE",
            "GH",
            "GI",
            "GR",
            "GL",
            "GD",
            "GP",
            "GU",
            "GT",
            "GG",
            "GN",
            "GW",
            "GY",
            "HT",
            "HM",
            "VA",
            "HN",
            "HK",
            "HU",
            "IS",
            "IN",
            "ID",
            "IR",
            "IQ",
            "IE",
            "IM",
            "IL",
            "IT",
            "JM",
            "JP",
            "JE",
            "JO",
            "KZ",
            "KE",
            "KI",
            "KW",
            "KG",
            "LA",
            "LV",
            "LB",
            "LS",
            "LR",
            "LY",
            "LI",
            "LT",
            "LU",
            "MO",
            "MG",
            "MW",
            "MY",
            "MV",
            "ML",
            "MT",
            "MH",
            "MQ",
            "MR",
            "MU",
            "YT",
            "MX",
            "FM",
            "MD",
            "MC",
            "MN",
            "ME",
            "MS",
            "MA",
            "MZ",
            "MM",
            "NA",
            "NR",
            "NP",
            "NL",
            "NC",
            "NZ",
            "NI",
            "NE",
            "NG",
            "NU",
            "NF",
            "KP",
            "MK",
            "MP",
            "NO",
            "OM",
            "PK",
            "PW",
            "PS",
            "PA",
            "PG",
            "PY",
            "PE",
            "PH",
            "PN",
            "PL",
            "PT",
            "PR",
            "QA",
            "RE",
            "RO",
            "RU",
            "RW",
            "BL",
            "SH",
            "KN",
            "LC",
            "MF",
            "PM",
            "VC",
            "WS",
            "SM",
            "ST",
            "SA",
            "SN",
            "RS",
            "SC",
            "SL",
            "SG",
            "SX",
            "SK",
            "SI",
            "SB",
            "SO",
            "ZA",
            "GS",
            "KR",
            "SS",
            "ES",
            "LK",
            "SD",
            "SR",
            "SJ",
            "SE",
            "CH",
            "SY",
            "TW",
            "TJ",
            "TZ",
            "TH",
            "TL",
            "TG",
            "TK",
            "TO",
            "TT",
            "TN",
            "TR",
            "TM",
            "TC",
            "TV",
            "UG",
            "UA",
            "AE",
            "GB",
            "UM",
            "US",
            "UY",
            "UZ",
            "VU",
            "VE",
            "VN",
            "VG",
            "VI",
            "WF",
            "EH",
            "YE",
            "ZM",
            "ZW",
            "T1",
        ],
    },
}

TOPICS = {
    "data-science": {
        "name": "Data science & machine learning",
        "keywords": [
            "data-science",
            "datascience",
            "ml",
            "training-data",
            "model-training",
            "machine-learning",
            "machinelearning",
            "sentiment-analysis",
            "ai",
            "artificial-intelligence",
            "neural-net",
            "neural-nets",
            "data-analytics",
            "visualization",
            "data-visualization",
            "nlp",
            "object-detection",
            "computer-vision",
            "jupyter",
            "matplotlib",
            "deep-learning",
            "pytorch",
            "pydata",
            "opencv-python-library",
            "pandas",
            "numpy",
            "tensor",
            "tensorflow",
        ],
    },
    "backend-web": {
        "name": "Backend web development",
        "keywords": [
            "backend",
            "backend-web",
            "flask",
            "django",
            "werkzeug",
            "wsgi",
            "celery",
            "jinja",
        ],
    },
    "frontend-web": {
        "name": "Frontend web development",
        "keywords": [
            "frontend",
            "frontend-web",
            "javascript",
            "react",
            "reactjs",
            "css",
            "angular",
            "angularjs",
            "jquery",
            "vuejs",
            "vue",
            "webpack",
            "node",
            "nodejs",
        ],
    },
    "security-privacy": {
        "name": "Security & privacy",
        "keywords": [
            "security",
            "privacy",
            "cryptography",
            "oauth",
            "authorization",
            "authentication",
        ],
    },
    "devops": {
        "name": "DevOps",
        "keywords": [
            "devops",
            "cloud",
            "docker",
            "kubernetes",
            "container",
            "containers",
            "ansible",
            "serverless",
            "openshift",
            "aws",
            "linux",
            "ubuntu",
            "monitoring",
            "openid-connect",
            "oauth",
            "redis",
            "rabbitmq",
            "nosql",
            "postgres",
            "postgresql",
            "mysql",
            "database",
            "elasticsearch",
            "lucene",
            "solr",
            "terraform",
            "nginx",
        ],
    },
    "python": {
        "name": "Python development",
        "keywords": ["python", "django", "flask"],
    },
    "game-dev": {
        "name": "Game development",
        "keywords": ["gamedev", "minecraft", "godot", "game"],
    },
    "blockchain": {
        "name": "Blockchain",
        "keywords": [
            "blockchain",
            "ethereum",
            "bitcoin",
            "cryptocurrency",
            "hyperledger",
            "solidity",
        ],
    },
    "techwriting": {
        "name": "Technical writing",
        "keywords": ["technical-writing", "sphinx", "sphinx-doc", "mkdocs"],
    },
    "other": {
        "name": "Other",
        "keywords": [],
    },
}


def forwards(apps, schema_editor):
    """Add the initial region and topic data."""
    Topic = apps.get_model("adserver", "Topic")
    Keyword = apps.get_model("adserver", "Keyword")
    Region = apps.get_model("adserver", "Region")
    CountryRegion = apps.get_model("adserver", "CountryRegion")

    if Region.objects.all().count() == 0:
        for slug in REGIONS:
            region = Region.objects.create(
                name=REGIONS[slug]["name"],
                slug=slug,
                order=REGIONS[slug]["order"],
            )

            for code in REGIONS[slug]["countries"]:
                CountryRegion.objects.create(
                    country=code,
                    region=region,
                )

    if Topic.objects.all().count() == 0:
        for slug in TOPICS:
            topic = Topic.objects.create(
                name=TOPICS[slug]["name"],
                slug=slug,
            )

            for keyword in TOPICS[slug]["keywords"]:
                kw, _ = Keyword.objects.get_or_create(
                    slug=keyword,
                )
                topic.keywords.add(kw)


class Migration(migrations.Migration):

    dependencies = [
        ("adserver", "0071_region_topic_modeling"),
    ]

    operations = [
        # No need to go backwards
        # The models these write to are deleted in the previous migration
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
