# Generated by Django 3.2.14 on 2022-08-02 22:07
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0072_data_region_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublisher',
            name='record_offer_details',
            field=models.BooleanField(default=False, help_text='Record additional offer details for this publisher'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='record_offer_details',
            field=models.BooleanField(default=False, help_text='Record additional offer details for this publisher'),
        ),
    ]
