# Generated by Django 3.2.15 on 2022-10-14 22:50
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0073_record_offer_details_per_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublisher',
            name='cache_ads_duration',
            field=models.PositiveIntegerField(default=0, help_text='If cache_ads is True and duration > 0, use a custom duration instead of settings.ADSERVER_STICKY_DECISION_DURATION.'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='cache_ads_duration',
            field=models.PositiveIntegerField(default=0, help_text='If cache_ads is True and duration > 0, use a custom duration instead of settings.ADSERVER_STICKY_DECISION_DURATION.'),
        ),
    ]
