# Generated by Django 3.2.16 on 2023-01-13 21:46
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0074_publisher_custom_cache_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherImpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('decisions', models.PositiveIntegerField(default=0, help_text="The number of times the Ad Decision API was called. The server might not respond with an ad if there isn't inventory.", verbose_name='Decisions')),
                ('offers', models.PositiveIntegerField(default=0, help_text='The number of times an ad was proposed by the ad server. The client may not load the ad (a view) for a variety of reasons ', verbose_name='Offers')),
                ('views', models.PositiveIntegerField(default=0, help_text='Number of times the ad was legitimately viewed', verbose_name='Views')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Number of times the ad was legitimately clicked', verbose_name='Clicks')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, help_text='This value has not been multiplied by the revenue share percentage', max_digits=8, verbose_name='Daily revenue')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publisher_impressions', to='adserver.publisher')),
            ],
            options={
                'verbose_name_plural': 'Publisher impressions',
                'ordering': ('-date',),
                'unique_together': {('publisher', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AdvertiserImpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('decisions', models.PositiveIntegerField(default=0, help_text="The number of times the Ad Decision API was called. The server might not respond with an ad if there isn't inventory.", verbose_name='Decisions')),
                ('offers', models.PositiveIntegerField(default=0, help_text='The number of times an ad was proposed by the ad server. The client may not load the ad (a view) for a variety of reasons ', verbose_name='Offers')),
                ('views', models.PositiveIntegerField(default=0, help_text='Number of times the ad was legitimately viewed', verbose_name='Views')),
                ('clicks', models.PositiveIntegerField(default=0, help_text='Number of times the ad was legitimately clicked', verbose_name='Clicks')),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Daily spend')),
                ('advertiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advertiser_impressions', to='adserver.advertiser')),
            ],
            options={
                'verbose_name_plural': 'Advertiser impressions',
                'ordering': ('-date',),
                'unique_together': {('advertiser', 'date')},
            },
        ),
    ]
