# Generated by Django 3.2.17 on 2023-02-14 22:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0075_advertiser_publisher_daily_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='pacing_interval',
            field=models.PositiveIntegerField(default=86400),
        ),
        migrations.AddField(
            model_name='historicalflight',
            name='pacing_interval',
            field=models.PositiveIntegerField(default=86400),
        ),
    ]
