# Generated by Django 3.2.18 on 2023-02-28 00:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0078_sampled_ctr_for_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='prioritize_ads_ctr',
            field=models.BooleanField(default=False, help_text='If true, the ad server will automatically show ads with higher CTRs at a higher rate than ads with lower CTRs.', verbose_name='Prioritize ads by CTR'),
        ),
        migrations.AddField(
            model_name='historicalflight',
            name='prioritize_ads_ctr',
            field=models.BooleanField(default=False, help_text='If true, the ad server will automatically show ads with higher CTRs at a higher rate than ads with lower CTRs.', verbose_name='Prioritize ads by CTR'),
        ),
    ]
