# Generated by Django 3.2.18 on 2023-05-08 22:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0082_publisher_allowed_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublisher',
            name='allow_api_keywords',
            field=models.BooleanField(default=True, help_text='Whether to allow the ad API/client to send its own keywords for targeting.'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='allow_api_keywords',
            field=models.BooleanField(default=True, help_text='Whether to allow the ad API/client to send its own keywords for targeting.'),
        ),
    ]
