# Generated by Django 4.2.4 on 2023-08-23 21:11
import jsonfield.fields
from django.db import migrations
from django.db import models

import adserver.validators


class Migration(migrations.Migration):

    dependencies = [
        ("adserver", "0085_flight_hard_stop_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="prices",
            field=jsonfield.fields.JSONField(
                blank=True,
                help_text="Topic pricing matrix for this region",
                null=True,
                validators=[adserver.validators.TopicPricingValidator()],
                verbose_name="Topic prices",
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="selectable",
            field=models.BooleanField(
                default=False,
                help_text="Whether advertisers can select this region for new flights",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="selectable",
            field=models.BooleanField(
                default=False,
                help_text="Whether advertisers can select this region for new flights",
            ),
        ),
    ]
