# Generated by Django 4.2.4 on 2023-09-21 22:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("adserver", "0086_region_topic_pricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpublisher",
            name="allow_multiple_placements",
            field=models.BooleanField(
                default=False,
                help_text="Can this publisher have multiple placements on the same pageview",
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="allow_multiple_placements",
            field=models.BooleanField(
                default=False,
                help_text="Can this publisher have multiple placements on the same pageview",
            ),
        ),
    ]
