# Generated by Django 4.2.4 on 2023-10-10 22:08
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0012_2_8"),
        ("adserver", "0087_publisher_allow_multiple_placements"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="djstripe.coupon",
            ),
        ),
        migrations.AddField(
            model_name="historicalflight",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="djstripe.coupon",
            ),
        ),
    ]
