# Generated by Django 4.2.4 on 2023-10-16 21:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("adserver", "0088_linked_discounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="click",
            name="is_proxy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="click",
            name="paid_eligible",
            field=models.BooleanField(
                default=None,
                help_text="Whether the impression was eligible for a paid ad",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="is_proxy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offer",
            name="paid_eligible",
            field=models.BooleanField(
                default=None,
                help_text="Whether the impression was eligible for a paid ad",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="view",
            name="is_proxy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="view",
            name="paid_eligible",
            field=models.BooleanField(
                default=None,
                help_text="Whether the impression was eligible for a paid ad",
                null=True,
            ),
        ),
    ]
