# Generated by Django 4.2.4 on 2024-01-04 19:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("adserver", "0089_paid_eligible_isproxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="click",
            name="rotations",
            field=models.PositiveSmallIntegerField(
                default=None, null=True, verbose_name="Number of ad rotations"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="rotations",
            field=models.PositiveSmallIntegerField(
                default=None, null=True, verbose_name="Number of ad rotations"
            ),
        ),
        migrations.AddField(
            model_name="view",
            name="rotations",
            field=models.PositiveSmallIntegerField(
                default=None, null=True, verbose_name="Number of ad rotations"
            ),
        ),
    ]
