# Generated by Django 4.2.4 on 2024-01-10 22:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("adserver", "0090_ads_rotated"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpublishergroup",
            name="default_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether this publisher group is enabled on new campaigns by default",
            ),
        ),
        migrations.AddField(
            model_name="publishergroup",
            name="default_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether this publisher group is enabled on new campaigns by default",
            ),
        ),
    ]
