# Generated by Django 4.2.4 on 2024-03-01 00:18
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("adserver", "0092_payout_method_github_sponsors"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpublisher",
            name="ignore_mobile_traffic",
            field=models.BooleanField(
                default=False,
                help_text="If true, no ads will be served to this publisher's mobile users",
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="ignore_mobile_traffic",
            field=models.BooleanField(
                default=False,
                help_text="If true, no ads will be served to this publisher's mobile users",
            ),
        ),
    ]
