# Generated by Django 4.2.11 on 2024-06-03 22:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("adserver", "0094_alter_advertisement_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="auto_renew",
            field=models.BooleanField(
                default=False, verbose_name="Automatically renew when complete"
            ),
        ),
        migrations.AddField(
            model_name="historicalflight",
            name="auto_renew",
            field=models.BooleanField(
                default=False, verbose_name="Automatically renew when complete"
            ),
        ),
    ]
