# Generated by Django 5.0.7 on 2024-07-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adserver", "0095_flight_auto_renew_historicalflight_auto_renew"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaladtype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical ad type",
                "verbose_name_plural": "historical ad types",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaladvertisement",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical advertisement",
                "verbose_name_plural": "historical advertisements",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaladvertiser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical advertiser",
                "verbose_name_plural": "historical advertisers",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcampaign",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical campaign",
                "verbose_name_plural": "historical campaigns",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalflight",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical flight",
                "verbose_name_plural": "historical flights",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpublisher",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical publisher",
                "verbose_name_plural": "historical publishers",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpublishergroup",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical publisher group",
                "verbose_name_plural": "historical publisher groups",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpublisherpayout",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical publisher payout",
                "verbose_name_plural": "historical publisher payouts",
            },
        ),
        migrations.AlterField(
            model_name="historicaladtype",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaladvertisement",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaladvertiser",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcampaign",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalflight",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpublisher",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpublishergroup",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpublisherpayout",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
