# Generated by Django 5.0.8 on 2024-09-30 21:04

import adserver.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adserver", "0096_simple_history_upgrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="click",
            name="keywords",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Keyword targeting for this view"
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="targeting_parameters",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[adserver.validators.TargetingParametersValidator()],
                verbose_name="Targeting parameters",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="traffic_cap",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                validators=[adserver.validators.TrafficFillValidator()],
                verbose_name="Traffic cap",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="traffic_fill",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                validators=[adserver.validators.TrafficFillValidator()],
                verbose_name="Traffic fill",
            ),
        ),
        migrations.AlterField(
            model_name="historicalflight",
            name="targeting_parameters",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[adserver.validators.TargetingParametersValidator()],
                verbose_name="Targeting parameters",
            ),
        ),
        migrations.AlterField(
            model_name="historicalflight",
            name="traffic_cap",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                validators=[adserver.validators.TrafficFillValidator()],
                verbose_name="Traffic cap",
            ),
        ),
        migrations.AlterField(
            model_name="historicalflight",
            name="traffic_fill",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                validators=[adserver.validators.TrafficFillValidator()],
                verbose_name="Traffic fill",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="keywords",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Keyword targeting for this view"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="prices",
            field=models.JSONField(
                blank=True,
                help_text="Topic pricing matrix for this region",
                null=True,
                validators=[adserver.validators.TopicPricingValidator()],
                verbose_name="Topic prices",
            ),
        ),
        migrations.AlterField(
            model_name="view",
            name="keywords",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Keyword targeting for this view"
            ),
        ),
    ]
