# Generated by Django 5.0.7 on 2024-08-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adserver", "0096_simple_history_upgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertiser",
            name="show_keyword_report",
            field=models.BooleanField(
                default=False,
                help_text="Show the link to the Keyword Report in the advertiser dashboard",
            ),
        ),
        migrations.AddField(
            model_name="advertiser",
            name="show_topic_report",
            field=models.BooleanField(
                default=False,
                help_text="Show the link to the Topic Report in the advertiser dashboard",
            ),
        ),
        migrations.AddField(
            model_name="historicaladvertiser",
            name="show_keyword_report",
            field=models.BooleanField(
                default=False,
                help_text="Show the link to the Keyword Report in the advertiser dashboard",
            ),
        ),
        migrations.AddField(
            model_name="historicaladvertiser",
            name="show_topic_report",
            field=models.BooleanField(
                default=False,
                help_text="Show the link to the Topic Report in the advertiser dashboard",
            ),
        ),
    ]
