# Generated by Django 5.0.12 on 2025-04-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0102_switch_uuid7'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='daily_cap',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='A daily maximum this flight can spend.', max_digits=8, null=True, verbose_name='Daily maximum spend cap'),
        ),
        migrations.AddField(
            model_name='historicalflight',
            name='daily_cap',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='A daily maximum this flight can spend.', max_digits=8, null=True, verbose_name='Daily maximum spend cap'),
        ),
    ]
