# Generated by Django 5.0.12 on 2025-05-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0103_flight_daily_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='auto_renew_payment_method',
            field=models.CharField(blank=True, choices=[('Issue a monthly invoice', 'Issue a monthly invoice'), ('Charge the card on file', 'Charge the card on file')], default=None, max_length=100, null=True, verbose_name='Auto renewal payment method'),
        ),
        migrations.AddField(
            model_name='historicalflight',
            name='auto_renew_payment_method',
            field=models.CharField(blank=True, choices=[('Issue a monthly invoice', 'Issue a monthly invoice'), ('Charge the card on file', 'Charge the card on file')], default=None, max_length=100, null=True, verbose_name='Auto renewal payment method'),
        ),
    ]
