# Generated by Django 5.2.8 on 2026-02-03 00:12

import adserver.analyzer.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0104_auto_renew_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublisher',
            name='send_bid_rate',
            field=models.BooleanField(default=False, help_text='Return the bid CPM/CPC with the decision API'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='send_bid_rate',
            field=models.BooleanField(default=False, help_text='Return the bid CPM/CPC with the decision API'),
        ),
        migrations.AlterField(
            model_name='historicalpublisher',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe (Bank transfer, debit card)'), ('paypal', 'PayPal'), ('opencollective', 'Open Collective'), ('github', 'GitHub sponsors'), ('other', 'Other')], default=None, help_text='How this publisher wants to get paid', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe (Bank transfer, debit card)'), ('paypal', 'PayPal'), ('opencollective', 'Open Collective'), ('github', 'GitHub sponsors'), ('other', 'Other')], default=None, help_text='How this publisher wants to get paid', max_length=100, null=True),
        ),
    ]
