# Generated by Django 5.2.11 on 2026-03-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0106_add_advertiser_flight_logos'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='auto_renew_notified',
            field=models.BooleanField(default=False, help_text='Whether the user has been notified of their flight renewal', verbose_name='Auto renew notification sent'),
        ),
        migrations.AddField(
            model_name='historicalflight',
            name='auto_renew_notified',
            field=models.BooleanField(default=False, help_text='Whether the user has been notified of their flight renewal', verbose_name='Auto renew notification sent'),
        ),
    ]
