#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Don't auto-migrate locally because this can cause weird issues when testing migrations
# python manage.py migrate
python manage.py runserver 0.0.0.0:5000
