# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-04 20:47
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0003_publisher-advertiser-adtype'),
        ('adserver_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advertisers',
            field=models.ManyToManyField(to='adserver.Advertiser'),
        ),
        migrations.AddField(
            model_name='user',
            name='publishers',
            field=models.ManyToManyField(to='adserver.Publisher'),
        ),
    ]
