# Generated by Django 5.0.7 on 2024-07-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adserver_auth", "0005_notify_completed_flights"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaluser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical user",
                "verbose_name_plural": "historical users",
            },
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
