# Generated by Django 5.0.7 on 2024-08-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adserver_auth", "0006_simple_history_upgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="flight_notifications",
            field=models.BooleanField(
                default=True, help_text="Receive email notification about ad flights"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="flight_notifications",
            field=models.BooleanField(
                default=True, help_text="Receive email notification about ad flights"
            ),
        ),
    ]
