# Generated by Django 5.0.7 on 2024-08-16 22:01

from django.db import migrations


def forwards(apps, schema_editor):
    """Update flight notifications field."""
    User = apps.get_model("adserver_auth", "User")

    for user in User.objects.all():
        user.flight_notifications = user.notify_on_completed_flights
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("adserver_auth", "0007_rename_flight_notifications"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
