# Generated by Django 5.2.7 on 2025-11-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adserver', '0104_auto_renew_payment_method'),
        ('adserver_auth', '0010_data_all_emails_verified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useradvertisermember',
            unique_together={('user', 'advertiser')},
        ),
    ]
