name: Continuous Integration Checks

# All branches
on: push

jobs:
  build:

    name: Unit tests and code style checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # https://docs.astral.sh/uv/guides/integration/github/
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          # Install a specific version of uv.
          version: "0.11.1"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install test dependencies
        run: |
          uv tool install tox --with tox-uv

      - name: Run CI
        run: |
          uv run tox
